rbac:
  nodeAccess: true

logLevel: info
podLabels:
  appName: fluentbit
config:
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Buffer_Size         0

    [FILTER]
        Name    lua
        Match   kube.*
        call    cb_replace
        code function cb_replace(tag, timestamp, record) if record["kubernetes"] then if record["kubernetes"]["labels"] then if record["kubernetes"]["labels"]["appName"] then record["appName"] = record["kubernetes"]["labels"]["appName"] end end end return 2, timestamp, record end

  outputs: |
    [OUTPUT]
        Name opensearch
        Match kube.*
        Host opensearch-cluster-master
        Logstash_Format On
        Retry_Limit 2
        HTTP_User admin
        HTTP_Passwd xaW4w1NIpl!
        Index kube-logs
        tls        On
        tls.verify Off
        Suppress_Type_Name On

    [OUTPUT]
        Name opensearch
        Match host.*
        Host opensearch-cluster-master
        Logstash_Format On
        Retry_Limit 2
        HTTP_User admin
        HTTP_Passwd xaW4w1NIpl!
        Index node
        tls        On
        tls.verify Off
        Suppress_Type_Name On
