fullnameOverride: postgres-svc
primary:
  service:
    type: NodePort
  initdb:
    scripts:
      000_init.sql: |
        CREATE DATABASE testdb;

podAnnotations:
  fluentbit.io/exclude: "true"

auth:
  username: "testuser"
  password: "testpassword"
  database: "testdb"

